[[rules]]
# Force re-cythonize
version = '== 1.56.2'
patch = 'grpcio-1.56.2.patch'
license = 'Apache-2.0'

[[rules]]
# Force re-cythonize + other fixes
version = '== 1.60.0'
patch = 'grpcio-1.60.0.patch'
license = 'Apache-2.0'
