[[rules]]
version = '== 3.0.10'
patch = 'Cython-3.0.10.patch'
license = 'Apache-2.0'

[[rules]]
version = '== 0.29.37'
patch = 'Cython-0.29.37.patch'
license = 'Apache-2.0'

[[rules]]
version = '== 0.29.32'
patch = 'Cython-0.29.32.patch'
license = 'Apache-2.0'
