[[rules]]
version = '== 3.4.7'
patch = 'cryptography-3.4.7.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '== 38.0.0'
patch = 'cryptography-38.0.0.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '>= 38.0.1, < 39.0.0'
patch = 'cryptography-38.0.1.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '>= 39.0.0, < 39.0.2'
patch = 'cryptography-39.0.0.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '>= 39.0.2, < 41.0.0'
patch = 'cryptography-39.0.2.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '>= 41.0.0, < 42.0.0'
patch = 'cryptography-41.0.0.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '>= 42.0.0, < 42.0.5'
patch = 'cryptography-42.0.0.patch'
license = 'Apache-2.0 OR BSD-3-Clause'

[[rules]]
version = '== 42.0.5'
patch = 'cryptography-42.0.5.patch'
license = 'Apache-2.0 OR BSD-3-Clause'
