[[rules]]
version = '== 2.2.2'
patch = 'pandas-2.2.2.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'

[[rules]]
version = '== 2.0.3'
patch = 'pandas-2.0.3.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'

[[rules]]
version = '== 1.5.2'
patch = 'pandas-1.5.2.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'
