[[rules]]
version = '== 0.19.1'
patch = 'torchvision-1.19.1.patch'
license = 'BSD-3-Clause'

[[add-sources]]
version = '0.19.1'
url = 'https://github.com/pytorch/vision/archive/refs/tags/v0.19.1.tar.gz'

[[rules]]
version = '== 0.17.1'
patch = 'torchvision-1.17.1.patch'
license = 'BSD-3-Clause'

[[add-sources]]
version = '0.17.1'
url = 'https://github.com/pytorch/vision/archive/refs/tags/v0.17.1.tar.gz'
