[[rules]]
version = '== 1.26.4'
patch = 'numpy-1.26.4.patch'
dist-type = 'sdist'
ignore-rule-on-llvm = true

[[rules]]
version = '== 1.23.5'
patch = 'numpy-1.23.5.patch'
dist-type = 'sdist'
# Keep this version as default for now
install-priority = 2

[[rules]]
# 1.23.2 is currently used by oldest-supported-numpy
version = '>= 1.23.2, < 1.23.5'
patch = 'numpy-1.23.2.patch'
dist-type = 'sdist'
