[[rules]]
version = '== 1.23.5'
patch = 'numpy-1.23.5.patch'
dist-type = 'sdist'

[[rules]]
# 1.23.2 is currently used by oldest-supported-numpy
version = '>= 1.23.2, < 1.23.5'
patch = 'numpy-1.23.2.patch'
dist-type = 'sdist'
