[[rules]]
version = '== 1.2.2'
patch = 'scikit-learn-1.2.2.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'

[[rules]]
version = '== 1.1.3'
patch = 'scikit-learn-1.1.3.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'
