[[rules]]
version = '== 2.15.0'
patch = 'tensorflow-2.15.0.patch'
license = 'Apache-2.0'

[[add-sources]]
version = '2.15.0'
url = 'https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.15.0.tar.gz'

[[rules]]
version = '== 2.14.0'
patch = 'tensorflow-2.14.0.patch'
license = 'Apache-2.0'

[[add-sources]]
version = '2.14.0'
url = 'https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.14.0.tar.gz'
