[[rules]]
version = '== 2.3.0'
patch = 'ray-2.3.0.patch'

[[add-sources]]
version = '2.3.0'
url = 'https://github.com/ray-project/ray/releases/download/ray-2.3.0/ray-2.3.0.tar.gz'

[[rules]]
version = '== 2.9.1'
patch = 'ray-2.9.1.patch'

[[add-sources]]
version = '2.9.1'
url = 'https://github.com/ray-project/ray/archive/refs/tags/ray-2.9.1.tar.gz'
