[[rules]]
version = '== 3.5.3'
patch = 'matplotlib-3.5.3.patch'
license = 'PSF-2.0'

[[rules]]
version = '== 3.6.3'
patch = 'matplotlib-3.6.3.patch'
license = 'PSF-2.0'

[[rules]]
# pin 3.7.0
install-priority = 10
version = '== 3.7.0'
patch = 'matplotlib-3.7.0.patch'
license = 'PSF-2.0'
