[[rules]]
version = '== 1.9.3'
patch = 'scipy-1.9.3.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'

[[rules]]
version = '== 1.10.1'
patch = 'scipy-1.10.1.patch'
license = 'BSD-3-Clause'
dist-type = 'sdist'
