[[rules]]
# Always pin a specific version. Our virtualenv seeder pins setuptools and pip to the bundled
# ones, so it makes sense to always pin wheel too to avoid it getting out of sync with setuptools.
version = '== 0.43.0'
# Add a workaround for building wheels with files larger than 2GB
patch = 'wheel-0.43.patch'
subdir = 'src'

# Catch all rule for newer versions
[[rules]]
version = '>= 0.43.0'
patch = 'wheel-0.43.patch'
subdir = 'src'
install-priority = 0

[[rules]]
version = '== 0.41.2'
patch = 'wheel-0.41.2.patch'
subdir = 'src'

[[rules]]
version = '>= 0.40, < 0.41.2'
patch = 'wheel-0.40.patch'
subdir = 'src'
install-priority = 0

[[rules]]
version = '== 0.38.*'
patch = 'wheel-0.38.patch'
subdir = 'src'
install-priority = 0

[[rules]]
version = '>= 0.36, < 0.38'
patch = 'wheel-0.37.patch'
subdir = 'src'
install-priority = 0

[[rules]]
version = '== 0.35.*'
patch = 'wheel-0.35.patch'
subdir = 'src'
install-priority = 0

[[rules]]
version = '< 0.35'
patch = 'wheel-pre-0.35.patch'
subdir = 'src'
install-priority = 0
